//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 APM.rc 使用
//
#define IDCANCEL                        2
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_INDICATOR_LABEL              101
#define IDC_PICT00                      111
#define IDC_PICT01                      112
#define IDC_PICT02                      113
#define IDC_PICT03                      114
#define IDC_PICT04                      115
#define IDC_PICT05                      116
#define IDC_PICT06                      117
#define IDC_PICT07                      118
#define IDC_PICT10                      119
#define IDC_PICT11                      120
#define IDC_PICT12                      121
#define IDC_PICT13                      122
#define IDC_PICT14                      123
#define IDC_PICT15                      124
#define IDC_PICT16                      125
#define IDC_PICT17                      126
#define IDC_PICT20                      127
#define IDR_MAINFRAME                   128
#define IDC_PICT21                      128
#define IDC_PICT22                      129
#define IDD_DIALOG_ERRORINFO            129
#define IDR_APMTYPE                     130
#define IDC_PICT23                      130
#define IDC_PICT24                      131
#define IDC_PICT25                      132
#define IDC_PICT26                      133
#define IDC_PICT27                      134
#define IDC_PICT30                      135
#define IDC_PICT31                      136
#define IDC_PICT32                      137
#define IDC_PICT33                      138
#define IDC_PICT34                      139
#define IDD_DIALOG_PROGRESS             139
#define IDC_PICT35                      140
#define IDC_PICT36                      141
#define IDC_PICT37                      142
#define IDC_PICT38                      143
#define IDC_PICT39                      144
#define IDC_PICT40                      145
#define IDC_PICT41                      146
#define IDD_DIALOG_IO                   166
#define IDB_BACK                        167
#define IDB_LEDLOW                      169
#define IDB_LEDHIGH                     170
#define IDD_DIALOG_HOME                 172
#define IDD_DIALOG_MONITOR              175
#define IDB_BITMAP_ERROR                179
#define IDD_DIALOG_LOGIN                180
#define IDD_CONTROLVIEW                 311
#define IDD_DIALOG_SETTING              312
#define IDD_DIALOG_MOTION               313
#define IDD_DIALOG_VISIONCTRL           314
#define IDD_DIALOG_HOMINGSETTING        315
#define IDD_DIALOG_PROJECTSETTING       316
#define IDD_DIALOG_LASERSETTING         317
#define IDD_DIALOG_MAIN                 318
#define IDR_MENU_MAIN                   319
#define IDD_DIALOG_NEWMAIN              319
#define IDD_DIALOG_PROJECT_CONFIRM      320
#define IDD_DIALOG_CJ_SETTING           320
#define IDB_BITMAP1                     323
#define IDI_ICON_STOP                   327
#define IDC_RADIO_LEFT                  1000
#define IDC_RADIO_RIGHT                 1001
#define IDC_COMBO_ORDER_TM              1002
#define IDC_COMBO_TM_TYPE               1003
#define IDC_BUTTON_MOVE_XL              1003
#define IDC_COMBO_ORDER_SS              1004
#define IDC_BUTTON_MOVE_XR              1004
#define IDC_COMBO_SS_TYPE               1005
#define IDC_BUTTON_MOVE_LYU             1005
#define IDC_BUTTON_MOVE_LYD             1006
#define IDC_BUTTON_MOVE_RYU             1007
#define IDC_BUTTON_MOVE_RYD             1008
#define IDC_GROUPBOX00                  1009
#define IDC_BUTTON_MOVE_ZU              1009
#define IDC_EDIT_CONTRAST               1010
#define IDC_GROUPBOX01                  1010
#define IDC_BUTTON_MOVE_ZD              1010
#define IDC_EDIT_SCORES                 1011
#define IDC_BUTTON_MOVE_LUU             1011
#define IDC_GROUPBOX10                  1012
#define IDC_BUTTON_MOVE_LUD             1012
#define IDC_GROUPBOX11                  1013
#define IDC_BUTTON_MOVE_RUU             1013
#define IDC_GROUPBOX20                  1014
#define IDC_BUTTON_MOVE_RUD             1014
#define IDC_GROUPBOX21                  1015
#define IDC_GROUPBOX30                  1016
#define IDC_GROUPBOX31                  1017
#define IDC_BUTTON_GOPOSITION           1017
#define IDC_EDIT_ERRORLIST				1017
#define IDC_BUTTON_SAVEPOSITION         1018
#define IDC_STATIC_ERRORLIST            1018
#define IDC_COMBO_SPACING               1019
#define IDC_COMBO_PRJNAME               1019
#define IDC_STATIC_TITLE                1019
#define IDC_EDIT_STRENGTH               1020
#define IDC_COMBO_CHECKTYPE             1020
#define IDC_EDIT_CHECK_ORDER            1020
#define IDC_EDIT_CIRCULARGAP            1021
#define IDC_EDIT_JOINT_ORDER            1021
#define IDC_BUTTON_SHOT_CALIBRATE       1021
#define IDC_EDIT_CIRCULARWIDTH          1022
#define IDC_SPIN_CHECK_ORDER            1022
#define IDC_EDIT_CIRCULARKERNEL         1023
#define IDC_SPIN_JOINT_ORDER            1023
#define IDC_EDIT_TARGET_MINW            1024
#define IDC_COMBO_VISIONTYPE            1024
#define IDC_EDIT_TARGET_MAXW            1025
#define IDC_EDIT_TARGET_MINH            1026
#define IDC_BUTTON_NEW                  1026
#define IDC_EDIT_TARGET_MAXH            1027
#define IDC_BUTTON_RELOAD               1027
#define IDC_EDIT_NEWPROJECT             1028
#define IDC_BUTTON_MATCH                1030
#define IDC_EDIT_MU_XVEL                1030
#define IDC_BUTTON_FINDTEST             1031
#define IDC_EDIT_MU_LYVEL               1031
#define IDC_BUTTON_SEARCHRECT           1032
#define IDC_EDIT_MU_RYVEL               1032
#define IDC_BUTTON_SEARCH_AREA          1033
#define IDC_EDIT_MU_ZVEL                1033
#define IDC_BUTTON_TEMPLATERECT         1034
#define IDC_BUTTON_WORKBENCHLOAD        1034
#define IDC_EDIT_MU_CXVEL               1034
#define IDC_BUTTON_REDLIGHT             1035
#define IDC_EDIT_MU_VZVEL               1035
#define IDC_STATIC_CONTAIN              1036
#define IDC_EDIT_AU_XVEL                1036
#define IDC_BUTTON_WORKBENCHLOAD2       1036
#define IDC_BUTTON_FIXER                1036
#define IDC_COMBO_JOINT_ORDER           1037
#define IDC_EDIT_AU_LYVEL               1037
#define IDC_COMBO_CIRCULARDIRECT        1038
#define IDC_TAB_CONTAINER               1038
#define IDC_BUTTON_PAD_CHECK            1038
#define IDC_EDIT_AU_RYVEL               1038
#define IDC_BUTTON_GETPOSITION          1039
#define IDC_EDIT_AU_ZVEL                1039
#define IDC_EDIT_PRODUCTROW             1040
#define IDC_BUTTON_PUSH_BALL            1040
#define IDC_EDIT_AU_CXVEL               1040
#define IDC_BUTTON_SHOT                 1041
#define IDC_EDIT_PRODUCTCOL             1041
#define IDC_EDIT_AU_VZVEL               1041
#define IDC_EDIT_PRODUCTX               1042
#define IDC_RADIO_WORKBENCH_LEFT        1042
#define IDC_EDIT_XACVEL                 1042
#define IDC_RADIO_WORKBENCH_RIGHT       1043
#define IDC_EDIT_PRODUCTY               1043
#define IDC_EDIT_LYACVEL                1043
#define IDC_STATIC_WORKSPACE            1044
#define IDC_EDIT_RYACVEL                1044
#define IDC_EDIT_ZACVEL                 1045
#define IDC_EDIT_VISIONNUM              1046
#define IDC_EDIT_CXACVEL                1046
#define IDC_EDIT_VZACVEL                1047
#define IDC_EDIT_JOINTNUM               1047
#define IDC_EDIT_WELDING_TIMES          1048
#define IDC_EDIT_TOP_EXPOSURE           1049
#define IDC_EDIT_JOINT_OFFSETX          1050
#define IDC_EDIT_BOTTOM_EXPOSURE        1050
#define IDC_EDIT_JOINT_OFFSETY          1051
#define IDC_EDIT_TOP_LIGHT              1051
#define IDC_EDIT_ZHEIGHT                1052
#define IDC_EDIT_BOTTOM_LIGHT           1052
#define IDC_EDIT_ZHEIGHT_ROW            1053
#define IDC_SPIN_TOP_E                  1053
#define IDC_SPIN_BOTTOM_E               1054
#define IDC_EDIT_ZHEIGHT_COL            1054
#define IDC_CHECK00                     1054
#define IDC_SPIN_TOP_L                  1055
#define IDC_CHECK01                     1055
#define IDC_SPIN_BOTTOM_L               1056
#define IDC_CHECK02                     1056
#define IDC_PROGRESS                    1056
#define IDC_CHECK03                     1057
#define IDC_STATIC_MESSAGE              1057
#define IDC_EDIT_NOZZLE_OFFSETX         1057
#define IDC_CHECK04                     1058
#define IDC_ANIMATE                     1058
#define IDC_EDIT_NOZZLE_OFFSETY         1058
#define IDC_CHECK05                     1059
#define IDC_EDIT_NOZZLE_OFFSETZ         1059
#define IDC_EDIT_NOZZLELIFE             1060
#define IDC_CHECK06                     1060
#define IDC_EDIT_BALL_NG                1061
#define IDC_CHECK07                     1061
#define IDC_CHECK10                     1062
#define IDC_CHECK11                     1063
#define IDC_CHECK12                     1064
#define IDC_CHECK13                     1065
#define IDC_CHECK14                     1066
#define IDC_CHECK15                     1067
#define IDC_CHECK16                     1068
#define IDC_CHECK17                     1069
#define IDC_CHECK_SAFETYGRATING         1070
#define IDC_CHECK20                     1070
#define IDC_CHECK_SAFETYGATE            1071
#define IDC_CHECK21                     1071
#define IDC_CHECK_CLEANNOZZLE           1072
#define IDC_CHECK22                     1072
#define IDC_EDIT_POWER                  1072
#define IDC_CHECK_FIXER                 1073
#define IDC_EDIT_PRESSURE               1073
#define IDC_CHECK23                     1073
#define IDC_CHECK24                     1074
#define IDC_CHECK_RANGING               1074
#define IDC_EDIT_BALL_PRESSURE_UP       1074
#define IDC_EDIT_BALL_PRESSURE_LOW      1075
#define IDC_COMBO_PRODUCT_ROW           1075
#define IDC_CHECK25                     1075
#define IDC_EDIT_ClEAN_POWER            1076
#define IDC_COMBO_PRODUCT_COL           1076
#define IDC_CHECK26                     1076
#define IDC_CHECK27                     1077
#define IDC_EDIT_TESTMODE_BALLNUM       1077
#define IDC_CHECK30                     1078
#define IDC_CHECK31                     1079
#define IDC_CHECK32                     1080
#define IDC_CHECK33                     1081
#define IDC_BUTTON_BOTTOMCHECK          1081
#define IDC_BUTTON_NOZZLE_CLEAN         1082
#define IDC_CHECK34                     1082
#define IDC_BUTTON_BALL_SUPPLY          1083
#define IDC_CHECK35                     1083
#define IDC_STATIC_CIRCLETIME           1084
#define IDC_CHECK36                     1084
#define IDC_STATIC_QUANTITY             1085
#define IDC_CHECK37                     1085
#define IDC_STATIC_LIFECYCLE            1086
#define IDC_BUTTON_RESET_COUNTER        1087
#define IDC_BUTTON_COUNTER_N            1088
#define IDC_CHECK_IDLING                1089
#define IDC_BUTTON_AUTO                 1090
#define IDC_BUTTON_STOP                 1091
#define IDC_STATIC_ACTUAL_X             1091
#define IDC_STATIC_ACTUAL_LY            1092
#define IDC_STATIC_ACTUAL_RY            1093
#define IDC_STATIC_ACTUAL_Z             1094
#define IDC_STATIC_ACTUAL_LU            1095
#define IDC_STATIC_ACTUAL_RU            1096
#define IDC_STATIC_ACTUAL_R             1097
#define IDC_CHECK_INCHING               1099
#define IDC_STATIC_TARGET               1100
#define IDC_COMBO_POSITION_TYPE         1101
#define IDC_BUTTON_APPLY                1104
#define IDC_BUTTON_CANCEL               1105
#define IDC_STATIC_XNLIMIT              1112
#define IDC_STATIC_LYNLIMIT             1113
#define IDC_STATIC_RYNLIMIT             1114
#define IDC_STATIC_ZNLIMIT              1115
#define IDC_STATIC_LUNLIMIT             1116
#define IDC_STATIC_RUNLIMIT             1117
#define IDC_STATIC_XHOME                1118
#define IDC_STATIC_LYHOME               1119
#define IDC_STATIC_RYHOME               1120
#define IDC_BUTTON_LOGIN                1120
#define IDC_STATIC_ZHOME                1121
#define IDC_STATIC_LUHOME               1122
#define IDC_STATIC_RUHOME               1123
#define IDC_STATIC_XPLIMIT              1124
#define IDC_STATIC_LYPLIMIT             1125
#define IDC_STATIC_RYPLIMIT             1126
#define IDC_STATIC_ZPLIMIT              1127
#define IDC_STATIC_LUPLIMIT             1128
#define IDC_STATIC_RUPLIMIT             1129
#define IDC_EDIT_PASSWORD               1129
#define IDC_STATIC_XALARM               1130
#define IDC_EDIT_OLDPASSWORD            1130
#define IDC_STATIC_LYALARM              1131
#define IDC_COMBO_USERTYPE              1131
#define IDC_STATIC_RYALARM              1132
#define IDC_STATIC_ZALARM               1133
#define IDC_STATIC_LUALARM              1134
#define IDC_STATIC_RUALARM              1135
#define IDC_STATIC_LASERSTS             1136
#define IDC_STATIC_N2PRESSURE           1137
#define IDC_STATIC_BALLSTS              1138
#define IDC_BUTTON_MOV_STOP             1139
#define IDC_STATIC_BUSY                 1139
#define IDC_COMBO_SEARCHAREA            1140
#define IDC_BUTTON_BOUND_HOME           1141
#define IDC_COMBO_JOINTS                1141
#define IDC_CHECK_CONTOUR               1142
#define IDC_CHECK_N2_READY              1143
#define IDC_CHECK_BINARY                1143
#define IDC_CHECK_BOND_READY            1144
#define IDC_BUTTON_MODIFY               1144
#define IDC_CHECK_APPOINT               1145
#define IDC_CHECK_MASK                  1145
#define IDC_STATIC_PRODUCT              1146
#define IDC_BUTTON_UPDATE               1150
#define IDC_BUTTON_UPDATE2              1151
#define IDC_BUTTON_SETTING              1152
#define IDC_BUTTON_UPDATE3              1152
#define IDC_BUTTON_UPDATE4              1153
#define IDC_COMBO_DISTANCE              1154
#define IDC_BUTTON_UPDATE5              1154
#define IDC_EDIT_RANGING1_X             1155
#define IDC_EDIT_RANGING1_Y             1156
#define IDC_EDIT_RANGING1_Z             1157
#define IDC_EDIT_RANGING2_X             1158
#define IDC_EDIT_RANGING2_Y             1159
#define IDC_EDIT_RANGING2_Z             1160
#define IDC_EDIT_RANGING3_X             1161
#define IDC_EDIT_RANGING3_Y             1162
#define IDC_EDIT_RANGING3_Z             1163
#define IDC_EDIT_RANGING4_X             1164
#define IDC_EDIT_RANGING4_Y             1165
#define IDC_EDIT_RANGING4_Z             1166
#define IDC_EDIT_RANGING5_X             1167
#define IDC_EDIT_RANGING5_Y             1168
#define IDC_EDIT_RANGING5_Z             1169
#define ID_OPTION_GENERALSETTING        32768
#define ID_OPTION_HOMINGSETTING         32769
#define ID_OPTION_LASERSETTING          32770
#define ID_PROJECT_CONFIGURATION        32771
#define ID_PROJECT_NEW                  32772
#define ID_OPERATION_HOME               32773
#define ID_OPERATION_AUTO               32774
#define ID_OPERATION_LASERTEST          32775
#define ID_VIEW_TOPCAMERA               32776
#define ID_VIEW_BOTTOMCAMERA            32777
#define ID_VIEW_IO                      32778
#define ID_SYSTEM_LOGIN                 32779
#define ID_RESET_STATUS                 32800
#define ID_BUTTON_STOP                  32803
#define ID_BUTTON_ZOOM                  32805
#define ID_BUTTON_LED                   32806
#define ID_32820                        32820
#define ID_OPTION_RANGING               32821

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        328
#define _APS_NEXT_COMMAND_VALUE         32822
#define _APS_NEXT_CONTROL_VALUE         1159
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
